spring:
  datasource:
    username: user
    password: user
    url: jdbc:postgresql://localhost:5432/user_db
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
         format_sql: false
